// Compact, read-only agent input. The full report remains the operator's comparison view.
// Generated by probe/validate; no CLI is run here and no catalog/evidence file is changed.
import { join } from 'node:path';
import { scopeKey } from './compare.mjs';

export function buildHandoff({ report, snapshot, catalogDocument, repo, snapshotPath, reportPath }) {
  const script = 'skills/maintain-provider-model-catalogs/scripts/catalog-probe.mjs';
  return {
    schemaVersion: 1,
    kind: 'cats-catalog-probe-agent-handoff',
    snapshotPath,
    reportPath,
    snapshotCreatedAt: report.snapshotCreatedAt,
    catalogSourceDigest: report.catalogSourceDigest,
    policy: 'confirm-uncertainty',
    instructions: [
      'Read the catalog-probe skill reference, then only the provider references named below.',
      'Reuse this snapshot. Capture only missing or conflicting evidence; do not repeat a full probe.',
      'A new candidate may need one targeted recheck if its account list is known to flap.',
      'Preserve existing unobserved fields. Removal requires operator confirmation; absence alone never proves withdrawal.',
      'Write the supporting evidence fixture before editing. This file is an index, not a replacement for that fixture.',
      'After editing, generate the catalog and validate the same snapshot. Run the required focused tests.',
    ],
    commands: {
      cwd: repo,
      generate: ['npm', 'run', 'catalog:generate'],
      validate: ['node', script, 'validate', '--snapshot', snapshotPath],
    },
    operatorActions: report.scopes.flatMap((scope) => scope.findings
      .filter((finding) => finding.audience === 'operator')
      .map((finding) => ({ scope: scope.key, reason: finding.subject, action: finding.nextAction }))),
    scopes: report.scopes.filter((scope) => report.needsAgent.includes(scope.key)).map((summary) => {
      const source = snapshot.sources.find((item) => scopeKey(item) === summary.key);
      const catalog = catalogDocument.catalogs.find((item) => scopeKey(item) === summary.key);
      const findings = summary.findings.filter((finding) => finding.audience === 'agent');
      const entryIds = new Set(findings.map((finding) => finding.entry ?? finding.subject));
      const entries = (catalog?.models ?? []).filter((entry) => entryIds.has(entry.id));
      const wireIds = new Set([
        ...findings.map((finding) => finding.subject),
        ...entries.flatMap((entry) => [entry.execution.model,
          ...(entry.execution.variants ?? []).map((variant) => variant.model)]),
      ]);
      const rows = (source?.models ?? []).filter((row) => wireIds.has(row.id));
      return {
        key: summary.key,
        selectionMode: summary.selectionMode,
        catalog: summary.catalog,
        ...(catalog?.basis ? { basis: catalog.basis } : {}),
        source: summary.source,
        ...(source?.sourceEvidence ? { sourceEvidence: source.sourceEvidence } : {}),
        reference: join('skills', 'maintain-provider-model-catalogs', 'references', 'providers', `${summary.provider}.md`).split('\\').join('/'),
        findings,
        entries: entries.map((entry) => ({ ...entry, controls: entry.controls ?? catalog.shared_controls ?? [] })),
        rows,
        ...(rows.length && ['ok', 'degraded'].includes(source.status) ? {
          evidenceCommand: ['node', script, 'evidence', '--snapshot', snapshotPath, '--scope', summary.key,
            '--ids', rows.map((row) => row.id).join(',')],
        } : {}),
      };
    }),
  };
}
