#!/usr/bin/env bash

CATS_RUNTIME_LAUNCHD_LABEL="${CATS_RUNTIME_LAUNCHD_LABEL:-io.sammykenny2.cats-runtime}"
CATS_RUNTIME_LAUNCHD_PLIST_DIR="${CATS_RUNTIME_LAUNCHD_PLIST_DIR:-$HOME/Library/LaunchAgents}"
CATS_RUNTIME_LOG_DIR="${CATS_RUNTIME_LOG_DIR:-$HOME/Library/Logs/cats-runtime}"
CATS_RUNTIME_SUPPORT_DIR="${CATS_RUNTIME_SUPPORT_DIR:-$HOME/Library/Application Support/cats-runtime}"

LABEL="$CATS_RUNTIME_LAUNCHD_LABEL"
PLIST_DIR="$CATS_RUNTIME_LAUNCHD_PLIST_DIR"
PLIST_FILE="$PLIST_DIR/$LABEL.plist"
LOG_DIR="$CATS_RUNTIME_LOG_DIR"
STDOUT_LOG="$LOG_DIR/stdout.log"
STDERR_LOG="$LOG_DIR/stderr.log"
RUNNER_SCRIPT="$CATS_RUNTIME_SUPPORT_DIR/start-cats-runtime.sh"
